### ISSUE TITLE
Refactor Recommendation api

### ISSUE THREAD

**Issue by mrck** [bevrand/bevrand#365]
The recommendation API fails on production, because neo4j needs too long for startup.

This code needs to be changed.

- [x] Move database seeding to rec api
- [ ] Unittests
- [ ] Component test
- [ ] System test
- [x] Split functions to increase readability
- [x] Create package for jaeger
- [ ] Return useful errors

**Comment by joerivrij** [comment]
Suggestion: we might replace neo4j for redislabs graphdb. This might be more lightweight since neo4j is quite a hungry db.
